from sqlalchemy import Boolean, Column, ForeignKey, Integer, String, Float, Date
from sqlalchemy.orm import relationship
from datetime import date as date_type

from database import Base

# ----------------------------- Passing ----------------------------------
class Passing(Base):
    __tablename__ = "passing"

    index = Column(Integer)
    Rk = Column(Integer)
    Pick6 = Column(Integer)
    TD_Per = Column(Float)
    Int_Per = Column(Float)
    Sk = Column(Integer)
    Sk_Per = Column(Float)
    Yds_Att = Column(Float)
    Adj_Yds_Att = Column(Float)
    Adj_Net_Yds_Att = Column(Float)
    Yds_Per_Comp = Column(Float)
    Year = Column(Integer)
    Rate = Column(Float)
    Att = Column(Integer)
    Game = Column(Integer)
    Week = Column(Integer)
    Date = Column(Date)
    Age = Column(Integer)
    Cmp = Column(Integer)
    Inc = Column(Integer)
    Comp_Per = Column(Float)
    Yds = Column(Integer)
    TD = Column(Integer)
    Int = Column(Integer)
    Player = Column(String)
    Opp = Column(String)
    Result = Column(String)
    Day = Column(String)
    Win_Loss = Column(String)
    Score = Column(String)
    Pkcol = Column(String, primary_key=True)
    Pos = Column(String)
    Team = Column(String)
    Home_Away = Column(String)
# ----------------------------- Receiving ----------------------------------
class Receiving(Base):
    __tablename__ = "receiving"
    Yds_Rec = Column(Float)
    TD = Column(Integer)
    Ctch_Per = Column(Float)
    Yds_Tgt = Column(Float)
    First_Dwns = Column(Integer)
    Week = Column(Integer)
    Date = Column(Date)
    Age = Column(Integer)
    Year = Column(Integer)
    index = Column(Integer)
    Yds = Column(Integer)
    Tgt = Column(Integer)
    Rk = Column(Integer)
    Game = Column(Integer)
    Rec = Column(Integer)
    Pkcol = Column(String, primary_key=True)
    Player = Column(String)
    Day = Column(String)
    Team = Column(String)
    Home_Away = Column(String)
    Opp = Column(String)
    Result = Column(String)
    Pos = Column(String)
    Win_Loss = Column(String)
    Score = Column(String)
    
# ----------------------------- Rushing ----------------------------------

class Rushing(Base):
    __tablename__ = "rushing"
    Rk = Column(Integer)
    Game = Column(Integer)
    Yds_Att = Column(Float)
    TD = Column(Integer)
    First_Dwns = Column(Integer)
    Week = Column(Integer)
    Date = Column(Date)
    Age = Column(Integer)
    Year = Column(Integer)
    index = Column(Integer)
    Yds = Column(Integer)
    Att = Column(Integer)
    Pkcol = Column(String, primary_key=True)
    Player = Column(String)
    Day = Column(String)
    Team = Column(String)
    Home_Away = Column(String)
    Opp = Column(String)
    Result = Column(String) 
    Pos = Column(String)
    Win_Loss = Column(String)
    Score = Column(String)

# ---------------------------- Fantasy  ----------------------------------

class Fantasy(Base):
    __tablename__ = "fantasy"
    Week = Column(Integer)
    Date = Column(Date)
    PPR = Column(Float)
    DKPt = Column(Float)
    FDPt = Column(Float)
    FantPt = Column(Float)
    Rk = Column(Integer)
    Game = Column(Integer)
    Year = Column(Integer)
    index = Column(Integer)
    Score = Column(String)
    Pkcol = Column(String, primary_key=True)
    Player = Column(String)
    Day = Column(String)
    Age = Column(String)
    Team = Column(String)
    Home_Away = Column(String)
    Opp = Column(String)
    Result = Column(String)
    Pos = Column(String)
    Win_Loss = Column(String)
    Points = Column(Float)
